<?
                    $host = 'localhost'; // адрес сервера 
                    $database = 'u0722890_voffinew'; // имя базы данных
                    $user = 'u0722890_marvek'; // имя пользователя
                    $password = 'sosochek322'; // пароль
                    $link = mysqli_connect($host, $user, $password, $database) // подключаемся к серверу
                    or die("Ошибка " . mysqli_error($link));
                    $r=$link->set_charset("utf8");
                    
if($_GET['img']!="")
    {
        $img2=$_GET['img'];
        $sql="SELECT * FROM `top` WHERE img = '..".$img2."'";
        $sql = mysqli_query($link, $sql);
        $sql = mysqli_fetch_array($sql, MYSQLI_ASSOC);
        $score = $sql['score'];
    }
if(isset($_FILES) && $_FILES['img']['error'] == 0 && $_FILES['img']['tmp_name']!="")
                { // Проверяем, загрузил ли пользователь файл
                    $destiation_dir = dirname(__FILE__) .'/img/'.md5($_FILES['img']['tmp_name']).'.jpg';
                    move_uploaded_file($_FILES['img']['tmp_name'], $destiation_dir );
                    $img='../img/'.md5($_FILES['img']['tmp_name']).'.jpg';
                    $img2='/img/'.md5($_FILES['img']['tmp_name']).'.jpg';
                    $authorization = "SMdcT56bKZJG3cnbj96DFAJR" . ":" . "E8CHewAI8DlT34LjP5wPHgYNGiPM7cA0NCkhiSa7MAxSIzBJ";
                    $url = "https://api.everypixel.com/v1/quality_ugc?url=http://photohack.voffi.ru".$img2;

                    $curl = curl_init();
                    curl_setopt($curl, CURLOPT_USERPWD, $authorization);
                    curl_setopt($curl, CURLOPT_URL, $url);
                    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
                    $data = curl_exec($curl);
                    curl_close($curl);
                    
                    $json = json_decode($data);
                    $score=round($json->quality->score,3)*1000;
                    
                    
                    
                    $sql = mysqli_query($link, "INSERT INTO `top`(`img`, `score`) VALUES ('".$img."','".$score."')");
                    unset($_FILES);
                }
     $data = array(
          "image_url[1]" => "http://photohack.voffi.ru".$img2, 
          "rotate[1]" => "0",
          "flip[1]" => "0",
          "crop[1]" => "0,0,1,1",
          "template_name" => "2312"
          );                                                                                  
       
      // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();
        
        curl_setopt($ch, CURLOPT_URL, 'http://api-soft.photolab.me/template_process.php');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
        
        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);
        $phimg = $result;

?>
<html>
<head>
  <title><?='Мое фото набрало '.$score.' очков в рейтинге. Сможешь побить мой рекорд?)'?></title>
  <meta property="og:url"           content="http://photohack.voffi.ru/post.php?img=<?=$img2?>" />
  <meta property="og:type"          content="website" />
  <meta property="og:title"         content="<?='Мое фото набрало '.$score.' очков в рейтинге. Сможешь побить мой рекорд?)'?>" />
  <meta property="og:image"         content="<?=$phimg?>" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="style.css"></script>
</head>
<body>
<div class="container">
         <div class="row justify-content-center">
            <div class="col-sm-8"><br><center>
<h1><?='Фото набрало '.$score.' очков в рейтинге.'?></h1><br>
<div class="ch">
<a href="http://photohack.voffi.ru">Попробовать снова</a><br>
<br>
<img src="<?=$phimg?>" style="width: 250px;/>
  <!-- Load Facebook SDK for JavaScript -->
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>
<br>
  <!-- Your share button code -->
  <div class="fb-share-button" 
    data-href="http://photohack.voffi.ru/post.php?img=<?=$img2?>"
    data-layout="button_count">
  </div><br></center>
  </div>
<br>
<div class="col-sm-8"><br>
<table class="table">
  <tr>
    <th>#</th>
    <th>img</th>
    <th>score</th>
  </tr>
<?
                    $host = 'localhost'; // адрес сервера 
                    $database = 'u0722890_voffinew'; // имя базы данных
                    $user = 'u0722890_marvek'; // имя пользователя
                    $password = 'sosochek322'; // пароль
                    $link = mysqli_connect($host, $user, $password, $database) // подключаемся к серверу
                    or die("Ошибка " . mysqli_error($link));
                    $r=$link->set_charset("utf8");
                    
 $top="SELECT * FROM `top` ORDER BY `top`.`score` DESC";
     $top = mysqli_query($link, $top);
     $i=1;
       while ($tops = mysqli_fetch_array($top)) 
                            {
                                echo '
                                <tr>
                                <td>'.$i.'</td>
                                <td><img src="'.$tops['img'].'" style="width: 150px;"/></td>
                                <td>'.$tops['score'].'</td>
                              </tr>';
                              $i++;
                            }

?>

</table>
</div></div></div>
</body>
</html>