<?
                    $host = 'localhost'; // адрес сервера 
                    $database = 'u0722890_voffinew'; // имя базы данных
                    $user = 'u0722890_marvek'; // имя пользователя
                    $password = 'sosochek322'; // пароль
                    $link = mysqli_connect($host, $user, $password, $database) // подключаемся к серверу
                    or die("Error " . mysqli_error($link));
                    $r=$link->set_charset("utf8");
                    
if($_GET['img']!="")
    {
        $img2=$_GET['img'];
        $sql="SELECT * FROM `top` WHERE img = '..".$img2."'";
        $sql = mysqli_query($link, $sql);
        $sql = mysqli_fetch_array($sql, MYSQLI_ASSOC);
        $score = $sql['score'];
    }
if(isset($_FILES) && $_FILES['img']['error'] == 0 && $_FILES['img']['tmp_name']!="")
                { // Проверяем, загрузил ли пользователь файл
                    $destiation_dir = dirname(__FILE__) .'/img/'.md5($_FILES['img']['tmp_name']).'.jpg';
                    move_uploaded_file($_FILES['img']['tmp_name'], $destiation_dir );
                    $img='../img/'.md5($_FILES['img']['tmp_name']).'.jpg';
                    $img2='/img/'.md5($_FILES['img']['tmp_name']).'.jpg';
                    $authorization = "kK7FIAlS5KO51R0g6nQE19Z1" . ":" . "WwlacnYEcB5Cqm1scuko2N1e6S1yEj1aVfW2eoABeEKvt03n";
                    $url = "https://api.everypixel.com/v1/quality_ugc?url=http://ph.voffi.ru".$img2;

                    $curl = curl_init();
                    curl_setopt($curl, CURLOPT_USERPWD, $authorization);
                    curl_setopt($curl, CURLOPT_URL, $url);
                    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
                    $data = curl_exec($curl);
                    curl_close($curl);
                    
                    $json = json_decode($data);
                    $score=round($json->quality->score,3)*1000;
                    
                    
                   
                    $sql = mysqli_query($link, "INSERT INTO `top`(`img`, `score`) VALUES ('".$img."','".$score."')");
                    unset($_FILES);
                }
     $data = array(
          "image_url[1]" => "http://ph.voffi.ru".$img2, 
          "rotate[1]" => "0",
          "flip[1]" => "0",
          "crop[1]" => "0,0,1,1",
          "template_name" => "2312"
          );                                                                                  
       
      // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();
        
        curl_setopt($ch, CURLOPT_URL, 'http://api-soft.photolab.me/template_process.php');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
        
        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);
        $phimg = $result;
         $recomindation = array
                        (
                            1 => 'Your photo is not so good to post. It`s unfocused, overexposed or have got unbalanced composition. So, your photo could consist of screenshots of messages, logotypes or photos that are too blurred.
                                    Recomendations: Add some brightness, composition and change the pose on your photo. Always you could try to add some effects while using Photolab.',
                            2 => 'Your photo belongs to the "bad" category, which consists of everyday frames. These photos primitively reflect the surrounding reality and have a low technical quality.
                                    Recommendation: Try to adjust the illumination, add filters from PhotoLab',
                            3 => 'Your photo belongs to the category of "medium" photos make up the bulk of the Instagram user content. Some authors try their best: they look for the look and apply filters. A photo may be good, but we still see that they are not professionals.
                                    Recomendations: please add some brightness and contrast to your photo, and use PhotoLab filters to make your photo more attractive.',
                            4 => 'You have a good image, it looks like pictures of a typical Instagram blogger. Staged photos with thoughtful composition, using filters or retouching and without technical flaws.
                                    Recomendations: On this step of your photoblogging life you need to think of only perfect quality of photo. Make it more professional, and unique.',
                            5 => 'Excellent image, professional photo, made without flaws.
                                    Recommendation: Keep up the good work! You`re good!'
                        );
                    if(round($json->quality->score,2)<=0.2) $description = $recomindation[1];
                    if(round($json->quality->score,2)>0.2 and round($json->quality->score,2)<=0.4) $description = $recomindation[2];
                    if(round($json->quality->score,2)>0.4 and round($json->quality->score,2)<=0.6) $description = $recomindation[3];
                    if(round($json->quality->score,2)>0.6 and round($json->quality->score,2)<=0.8) $description = $recomindation[4];
                    if(round($json->quality->score,2)>0.8) $description = $recomindation[4];

?>
<html>
<head>
  <title><?='My photo typed '.$score.' points in the ranking. Can you beat my score?)'?></title>
  
  <meta property="og:url"           content="http://ph.voffi.ru/post.php?img=<?=$img2?>" />
  <meta property="og:type"          content="website" />
  <meta property="og:title"         content="<?='My photo typed '.$score.' points in the ranking. Can you beat my score?)'?>" />
  <meta property="og:description"   content="<?=$description?>" />
  <meta property="og:image"         content="<?=$phimg?>" />
  
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>
<div class="container">
         <div class="row justify-content-center">
            <div class="col-sm-8"><br><center>
<h1><?='Photo scored '.$score.' points in the ranking.'?></h1><br>
<div class="ch">
<a href="http://ph.voffi.ru">Try again</a><br>
<br>
<img src="<?=$phimg?>" style="width: 250px;"/>
<br><p id="h1" style="display:none"><?=$description?></p>


  <!-- Load Facebook SDK for JavaScript -->
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>
<br>
  <!-- Your share button code -->
  <div class="fb-share-button" 
    onClick="document.getElementById('h1').style.display='';return false;"
    data-href="http://ph.voffi.ru/post.php?img=<?=$img2?>"
    data-layout="button_count">
  </div><br></center>
  </div>
<br>
<div class="col-sm-8"><br>
<table class="table">
  <tr>
    <th>#</th>
    <th>img</th>
    <th>score</th>
  </tr>
<?
                    $host = 'localhost'; // адрес сервера 
                    $database = 'u0722890_voffinew'; // имя базы данных
                    $user = 'u0722890_marvek'; // имя пользователя
                    $password = 'sosochek322'; // пароль
                    $link = mysqli_connect($host, $user, $password, $database) // подключаемся к серверу
                    or die("Error " . mysqli_error($link));
                    $r=$link->set_charset("utf8");
                    
 $top="SELECT * FROM `top` ORDER BY `top`.`score` DESC";
     $top = mysqli_query($link, $top);
     $i=1;
       while ($tops = mysqli_fetch_array($top)) 
                            {
                                echo '
                                <tr>
                                <td>'.$i.'</td>
                                <td><img src="'.$tops['img'].'" style="width: 150px;"/></td>
                                <td>'.$tops['score'].'</td>
                              </tr>';
                              $i++;
                            }

?>

</table>
</div></div></div>
</body>
</html>